# Generated by Django 3.2.7 on 2022-01-09 12:47

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usertelegram_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahalla', models.CharField(max_length=100, verbose_name=api.models.Mahalla)),
                ('phone', models.CharField(max_length=17)),
                ('over_all_products', models.PositiveIntegerField(default=0)),
                ('km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dostavka', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.carttelegram')),
            ],
        ),
    ]
